language: python
dist: trusty
sudo: false
python:
  - "2.7"
install:
  - pip install --upgrade tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
notifications:
  irc:
    - "irc.freenode.org#rapidsms"
